import type { Metadata } from "next";
import { Inter, Cardo } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets:  ["greek", "latin"] });
// const cardo = Cardo({weight: "400", subsets:["greek", "greek-ext", "latin"]})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
