import type { Metadata } from "next";
import {Merriweather  } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/footer";

const merriWeather = Merriweather({ subsets: ['cyrillic', 'cyrillic-ext', 'latin', 'latin-ext', 'vietnamese'],
weight: ['300', '400', '700', '900']  });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body className={`${merriWeather.className} `}>
        <main className="min-h-screen flex-col justify-center items-center">
        <Navbar />
        {children}
        <Footer/>
        </main>
        </body>
    </html>
  );
}
